name: EasyCrypt compilation & check

on:
  workflow_dispatch:
  push:
    branches:
      - memory-ci

env:
  HOME: /home/charlie
  OPAMYES: true
  OPAMJOBS: 4

jobs:
  pre_job:
    name: Check for Duplicates Jobs
    runs-on: [self-hosted, linux, X64]
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - uses: fkirc/skip-duplicate-actions@v5
      id: skip_check
      with:
        concurrent_skipping: 'same_content_newer'
        skip_after_successful_duplicate: 'false'

  compile-opam:
    name: EasyCrypt compilation (opam)
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: [self-hosted, linux, X64]
    container:
      image: ghcr.io/easycrypt/ec-build-box
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Update OPAM & EasyCrypt dependencies
      run: |
        opam update
        opam pin add -n easycrypt .
        opam install --deps-only easycrypt
    - name: Compile EasyCrypt
      run: opam exec -- make

  compile-nix:
    name: EasyCrypt compilation (nix)
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    env:
      HOME: /home/runner
    runs-on: [self-hosted, linux, X64]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Nix
      uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup Cachix
      uses: cachix/cachix-action@v14
      with:
        name: formosa-crypto
        authToken: '${{ secrets.CACHIX_WRITE_TOKEN }}'
    - name: Build and cache EasyCrypt and dependencies
      run: |
        make nix-build-with-provers

  check:
    name: Check EasyCrypt Libraries
    needs: [pre_job, compile-opam]
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: [self-hosted, linux, X64]
    container:
      image: ghcr.io/easycrypt/ec-build-box
    strategy:
      fail-fast: false
      matrix:
        target: [unit, stdlib, examples]
    steps:
    - uses: actions/checkout@v4
    - name: Update OPAM & EasyCrypt dependencies
      run: |
        opam update
        opam pin add -n easycrypt .
        opam install --deps-only easycrypt
    - name: Compile EasyCrypt
      run: opam exec -- make
    - name: Detect SMT provers
      run: |
        rm -f ~/.why3.conf
        opam exec -- ./ec.native why3config -why3 ~/.why3.conf
    - name: Compile Library (${{ matrix.target }})
      env:
        TARGET: ${{ matrix.target }}
      run: opam exec -- make $TARGET
    - uses: actions/upload-artifact@v4
      name: Upload report.log
      if: always()
      with:
        name: report.log (${{ matrix.target }})
        path: report.log
        if-no-files-found: ignore

  fetch-external-matrix:
    name: Fetch EasyCrypt External Projects Matrix
    needs: [pre_job, compile-opam]
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: [self-hosted, linux, X64]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: 'easycrypt'
    - id: set-matrix
      run: |
        JSON=$(jq -c . < easycrypt/.github/workflows/external.json)
        echo "matrix=${JSON}" >> $GITHUB_OUTPUT

  external:
    name: Check EasyCrypt External Projects
    needs: [fetch-external-matrix]
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: [self-hosted, linux, X64]
    container:
      image: ghcr.io/easycrypt/ec-build-box
    strategy:
      fail-fast: false
      matrix:
        target: ${{fromJson(needs.fetch-external-matrix.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v4
      with:
        path: easycrypt
    - name: Checkout External Project
      run: |
        git clone --recurse-submodules \
          -b ${{ matrix.target.branch }} \
          ${{ matrix.target.repository }} \
          project/${{ matrix.target.name }}
    - name: Update OPAM & EasyCrypt dependencies
      run: |
        opam update
        opam pin add -n easycrypt easycrypt
        opam install --deps-only easycrypt
    - name: Compile & Install EasyCrypt
      run: opam exec -- make -C easycrypt build install
    - name: Detect SMT provers
      run: |
        rm -f ~/.why3.conf ~/.config/easycrypt/why3.conf
        opam exec -- easycrypt why3config
    - name: Compile project
      working-directory: project/${{ matrix.target.name }}/${{ matrix.target.subdir }}
      run: |
        free; opam exec -- easycrypt runtest  \
          -report report.log            \
          -raw-args -gcstats            \
          -raw-args -compact            \
          -raw-args 20                  \
          ${{ matrix.target.options  }} \
          ${{ matrix.target.config   }} \
          ${{ matrix.target.scenario }}
    - name: Compute real-path to report.log
      if: always()
      run: |
        echo "report=$(realpath project/${{ matrix.target.name }}/${{ matrix.target.subdir }})/report.log" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      name: Upload report.log
      if: always()
      with:
        name: report.log (${{ matrix.target.name }})
        path: ${{ env.report }}
        if-no-files-found: ignore


